# Generated by Django 3.2 on 2022-03-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50, unique=True, verbose_name='Интервал')),
            ],
            options={
                'verbose_name': 'Интервал времени',
                'verbose_name_plural': 'Интервалы времени',
            },
        ),
        migrations.AlterModelOptions(
            name='reserved_cabinet',
            options={'verbose_name': 'Зарезервированные кабинеты', 'verbose_name_plural': 'Зарезервированные кабинеты'},
        ),
        migrations.AddField(
            model_name='cabinet',
            name='time_id',
            field=models.ManyToManyField(related_name='time_id', to='main.TimeInterval'),
        ),
    ]
