# Generated by Django 3.2 on 2022-03-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220324_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserved_cabinet',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='reserved_cabinet',
            name='start_time',
        ),
        migrations.AddField(
            model_name='reserved_cabinet',
            name='reserv_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Время'),
        ),
    ]
