# Generated by Django 3.2 on 2022-03-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_reserved_cabinet_reserv_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Отчество'),
        ),
    ]
