# Generated by Django 3.2 on 2022-03-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_customuser_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название ПО')),
            ],
            options={
                'verbose_name': 'Название ПО',
                'verbose_name_plural': 'Название ПО',
            },
        ),
        migrations.AddField(
            model_name='cabinet',
            name='equip_id',
            field=models.ManyToManyField(related_name='equip_id', to='main.Equipment'),
        ),
    ]
