# Generated by Django 3.2 on 2022-05-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_zayavka_wish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='wish',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Пожелание к оборудованию'),
        ),
    ]
