# Generated by Django 3.2 on 2022-05-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_zayavka_wish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Причина отказа'),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='wish',
            field=models.TextField(blank=True, default='', max_length=250, null=True, verbose_name='Пожелание к оборудованию'),
        ),
    ]
