# Generated by Django 3.2 on 2022-05-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20220523_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='number',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Номер лаборатории'),
        ),
    ]
