# Generated by Django 3.2 on 2022-05-23 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_cabinet_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserved_cabinet',
            name='cab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cabinet'),
        ),
        migrations.AlterField(
            model_name='reserved_cabinet',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='zayavka_cab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cabinet'),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='zayavka_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zayavka_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
